spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/matching_db
    username: match
    password: matchpw124
  
  mvc:
    view:
      suffix: .html

  redis:
    port: 6379
    host: localhost

mybatis:
  type-aliases-package: com.match
  mapper-locations: mapper/*.xml
  configuration:
      map-underscore-to-camel-case: true
  